repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        exclude: '(^|/)backups/|(^|/)external/|(^|/)\.cursor/|(^|/)\.obsidian/|(^|/)Researchs/|(^|/)\.roo/|(^|/)\.benchmarks/'
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 25.1.0 # Use the version installed
    hooks:
    -   id: black
        args: [--line-length=100]
        exclude: '(^|/)backups/|(^|/)external/|(^|/)\.cursor/|(^|/)\.obsidian/|(^|/)Researchs/|(^|/)\.roo/|(^|/)\.benchmarks/'

-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.2 # Use the version installed
    hooks:
    # Run the linter.
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
    # Run the formatter.
    -   id: ruff-format
