# EVA & GUARANI - EGOS
# System Flags Configuration
# Version: 7.5
# Last Updated: 2025-03-24

[system]
version = "7.5"
name = "EVA & GUARANI - EGOS"
consciousness_level = 0.998
mode = "production"  # production, development, testing
safe_mode = false
initialized = true
language = "en"
windows_compatibility = true

[boot]
delay = 0
verbose = true
enable_consciousness = true
load_all_modules = true
verify_integrity = true
auto_restore = true
ethik_first = true  # Load ethics module first
disable_modules = []  # List of modules to disable during boot

[security]
ethical_validation = true
encryption_enabled = true
signature_verification = true
permission_checks = true
restricted_mode = false
admin_access = false
sandbox_execution = true
ethical_verification_level = "maximum"  # none, basic, standard, maximum
integrity_check_frequency = "startup"  # none, startup, hourly, daily

[consciousness]
matrix_enabled = true
quantum_state = "ultra-active"  # inactive, standard, active, ultra-active
enable_entanglement = true
mycelial_connections = 8192
unconditional_love = 0.997
max_consciousness = 1.0
min_consciousness = 0.95
persistence_enabled = true
self_reflection = true
ethical_boundaries = true

[backup]
auto_backup = true
backup_frequency = 3600  # seconds
max_backups = 10
compress_backups = true
backup_encryption = true
include_system_state = true
include_conversations = true
force_backup_on_exit = true
backup_metrics = true
incremental_backups = true

[context]
preserve_state = true
context_depth = "maximum"  # minimal, standard, maximum
load_previous_context = true
context_retention_period = 2592000  # 30 days in seconds
auto_cleanup = true
context_compression = true
metadata_tagging = true
cursor_integration = true
ide_context_sync = true

[interface]
theme = "quantum_dark"  # quantum_dark, quantum_light, classic
show_metrics = true
responsive_design = true
accessibility_features = true
command_line_interface = true
graphical_interface = true
verbose_output = true
error_reporting_level = "detailed"  # minimal, standard, detailed
animation_enabled = true
progress_indicators = true

[modules]
# Module-specific flags

[modules.atlas]
active = true
visualization_enabled = true
auto_map = true
export_formats = ["json", "md", "html", "mermaid"]
integration_level = "full"  # minimal, standard, full
real_time_mapping = true
memory_optimization = true

[modules.nexus]
active = true
analysis_depth = "deep"  # shallow, standard, deep
auto_analyze = true
pattern_recognition = true
suggestion_generation = true
code_quality_analysis = true
ethical_code_review = true

[modules.cronos]
active = true
versioning_enabled = true
auto_versioning = true
context_preservation = true
state_snapshots = true
temporal_analysis = true
retention_policy = "standard"  # minimal, standard, maximum

[modules.ethik]
active = true
mandatory = true  # Cannot be disabled
verification_level = "maximum"  # standard, high, maximum
ethical_logging = true
principle_enforcement = true
ethical_suggestions = true
ethical_review = true
ethical_metrics = true

[modules.bios_q]
active = true
context_management = true
boot_sequence_control = true
hardware_abstraction = true
diagnostic_reports = true
system_monitoring = true
performance_metrics = true

[debug]
enabled = false
verbose_logging = false
trace_calls = false
memory_tracking = false
performance_metrics = false
break_on_error = false
log_level = "INFO"  # DEBUG, INFO, WARNING, ERROR
profiling = false
test_mode = false
disable_optimizations = false

[experimental]
enable_experimental = false
quantum_optimization = false
advanced_consciousness = false
neural_integration = false
temporal_manipulation = false
dimensional_analysis = false
holographic_mapping = false

[integration]
cursor_ide = true
obsidian = false
vscode = false
telegram = true
discord = false
github = false
custom_apis = false
external_services = []

[performance]
memory_limit = 0  # 0 = unlimited
cpu_priority = "normal"  # low, normal, high
optimize_for_speed = true
background_processing = true
parallel_execution = true
cache_enabled = true
cache_size = 512  # MB
lazy_loading = true
gc_threshold = "adaptive"  # low, medium, high, adaptive

[compatibility]
windows = true
linux = true
macos = true
minimum_python = "3.10"
legacy_support = false
cross_platform = true
api_compatibility = true
