---
metadata:
  api_endpoints: []
  author: EVA & GUARANI
  backup_required: true
  category: modules
  changelog: []
  dependencies:
  - TRANSLATOR
  - QUANTUM_PROMPTS
  - BIOS-Q
  description: Component of the EVA & GUARANI Quantum Unified System
  documentation_quality: 0.95
  encoding: utf-8
  ethical_validation: true
  last_updated: '2025-03-29'
  related_files: []
  required: true
  review_status: approved
  security_level: 0.95
  simulation_capable: false
  status: active
  subsystem: TRANSLATOR
  test_coverage: 0.9
  translation_status: completed
  type: configuration
  version: '8.0'
  windows_compatibility: true
---
# EVA & GUARANI Translator Configuration
# Default settings optimized for cost efficiency

engine:
  # Default translation engine (huggingface or openai)
  name: huggingface
  
  # Engine-specific settings
  # HuggingFace configuration (offline, free)
  model: Helsinki-NLP/opus-mt-pt-en
  max_tokens: 4096
  temperature: 0.3
  
  # OpenAI settings (only used when engine is set to openai)
  # api_key: null  # Set your API key here or use OPENAI_API_KEY environment variable
  
  # Cost control settings
  cost_control:
    enabled: true
    monthly_budget: 5.00  # Monthly budget in USD
    warn_at_percent: 80   # Warn when this percentage of the budget is reached

cache:
  enabled: true
  directory: data/cache
  max_size: 1000000000  # 1GB max cache size
  ttl: 2592000          # 30 days in seconds (time-to-live for cache entries)

# File scanning settings
scanner:
  recursive: true
  ignore_dirs:
    - .git
    - __pycache__
    - venv
    - env
    - node_modules
    - bin
    - lib
    - build
    - dist
    - .vscode
  ignore_files:
    - "*.exe"
    - "*.dll"
    - "*.so"
    - "*.pyc"
    - "*.pyo"
    - "*.bin"
    - ".DS_Store"
    - "Thumbs.db"

# Technical terminology settings
terminology:
  enabled: true
  dictionary_file: config/technical_terms.json
  preserve_case: true
  preserve_format: true

# UI settings
ui:
  show_progress_bars: true
  detailed_stats: true
  verbose_output: false
  save_session: true
  session_file: translator_session.json

# OpenAI specific configuration
# Used when engine.name is set to "openai"
openai:
  max_tokens: 1000      # Reduced to control costs
  model: gpt-3.5-turbo  # More economical model (not gpt-4)
  temperature: 0.3

# Output report file
report_output: translation_report.md
backup_originals: true 