engine:
  name: huggingface  # Usando HuggingFace como engine padrão para economizar custos
  api_key: null      # Apenas necessário para OpenAI
  model: Helsinki-NLP/opus-mt-pt-en
  max_tokens: 4096
  temperature: 0.3
  cost_control:
    enabled: true
    monthly_budget: 5.00  # Limite mensal em dólares
    warn_at_percent: 80   # Avisar quando atingir 80% do orçamento

openai:
  max_tokens: 2048       # Reduzido para controlar custos
  model: gpt-3.5-turbo   # Modelo mais econômico
  temperature: 0.3
  
scanner:
  ignore_dirs:
    - .git
    - __pycache__
    - node_modules
    - venv
    - dist
    - build
  file_extensions:
    - .py
    - .md
    - .txt
    - .js
    - .html
    - .json
    - .yaml
    - .yml
  
cache:
  enabled: true
  directory: ./cache
  max_size: 1000000000  # 1GB
  ttl: 2592000          # 30 dias em segundos

report_output: translation_report.md
backup_originals: true 